Feature/homework 5 room
Dumankrg2019/IntensiveAndroid pull request #8
Opened 2023-01-06 06:05 UTC by Dumankrg2019

2023-01-20 19:48 UTC, AndroidStudentClub requested changes
Проверил

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/build.gradle
> +    implementation "androidx.room:room-ktx:2.4.3"
Версии лучше в константы)

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/network/MovieApiInterface.kt
> +import ru.androidschool.intensiv.domain.models.MovieResponse
на мой взгляд модельки лучше в data слой, в domain обычно логика содержится

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/room/likely_movies/LikeMovieDao.kt
> +    fun deleteItemInLikelyMovieDB(id: Int): Completable
Тут и должен быть Completable - так как нам не нужно получать какой-то результат, а нужно просто статус получить

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/room/likely_movies/LikeMovieDao.kt
> +    fun insertLikelyMovie(movies:LikelyMovie): Completable
Если на не нужно возвращать какой-то результат, то Completable - ок

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/room/likely_movies/LikeMovieDao.kt
> +    fun getAllLikelyMovies(): LiveData<List<LikelyMovie>>
А чего тут LiveData? Должен быть Single

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/room/likely_movies/LikeMovieDao.kt
> +    fun insertAll(vararg movies:LikelyMovie):List<Long>
Тут должен быть Completable

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/room/likely_movies/LikelyMovie.kt
> +    @SerializedName("overview")
Тут есть проблема что в одной модели смешиваются аннотации для разных целей.
Я бы рекомендовал разделить
Использовать одну модель данных для сети
И другую для БД. Тогда и аннотации не надо будет смешивать

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/room/likely_movies/LikelyMovie.kt
> +    @SerializedName("release_date")
Зачем тут @SerializedName?

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/repository/LikelyMoviesRepository.kt
> +    val  allLikelyMovies: LiveData<List<LikelyMovie>> = likelyMoviesDao.getAllLikelyMovies()
А зачем LiveData? Можно через RxJava. LiveData не рекомендуется использовать в domain и data слоях

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/repository/LikelyMoviesRepository.kt
> +    suspend fun insert(likelyMoviesDao: LikeMovieDao) {
А тут и корутины) Как-то слишком много всего смешано и LiveData и Rx и корутины. Я бы предложил все через Rx сначала сделать. До корутин скоро дойдем

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/repository/TvShowListRepository.kt
> +        //в примере был .map {} - не понял для чего и как длбавлять
Map нужен как раз для трансформации из DTO в VO
DTO - это data классы которые нужны для работы с сетью
А VO - это то что мы уже используем внутри приложения на уровне Viewmodel или в Domain.
Маппинг нужен для независимости сетевого слоя. Это такой некий конвертор между разными типами данных.

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/repository/TvShowListRepository.kt
> +        //в примере был .map {} - не понял для чего и как длбавлять
Вот тут поподробнее https://www.baeldung.com/java-dto-pattern

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/repository/TvShowListRepository.kt
> +        //в примере был .map {} - не понял для чего и как длбавлять
И вот тут еще про мапинг https://habr.com/ru/company/mobileup/blog/335382/  раздел Заблуждение: Обязательность маппинга между слоями

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/repository/TvShowListRepository.kt
> +        //в примере был .map {} - не понял для чего и как длбавлять
Общий вывод такой: 
Если у вас сложное приложение с логикой бизнеса и логикой приложения, и/или разные люди работают над разными слоями, то лучше разделять данные между слоями (и маппить их). Также это стоит делать, если серверное API корявое. Но если вы работаете над проектом один, и это простое приложение, то не усложняйте лишним маппингом.

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/repository/TvShowListRepository.kt
> +        //в примере был .map {} - не понял для чего и как длбавлять
Так как мы учимся - то лучше попробовать сделать максимально гибко чтобы было понимание какие есть приемы

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/models/Movie.kt
>  data class Movie (
Можно пометить как MovieDto

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/domain/models/Movie.kt
>  data class Movie (
Лучше переместить в data слой и там создать папку dto и там все модели для сети использовать

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/movie_details/MovieDetailsFragment.kt
> +        val dbLikeMovie = LikelyMovieDatabase.get(requireActivity()).likeMovieDao()
Вот так можно requireActivity().applicationContext

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/movie_details/MovieDetailsFragment.kt
>              .subscribe(
А для этого экрана не использовать ViewModel?  Если бы тут была ViewModel то все запросы надо в ViewModel перенести

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/movie_details/MovieDetailsFragment.kt
> +        Handler(Looper.getMainLooper()).postDelayed(
А зачем Handler? Если у нас Rx то не надо

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/movie_details/MovieDetailsFragment.kt
> +                                if(it.id == movieId) {
Не совсем понятно зачем тут проверять. Если в БД уже будет значение, то значит фильм лайкнут -то сюда вернется значение по этому ID.

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/movie_details/MovieDetailsFragment.kt
> +                            //почему то вылетает ошибка, когда не совпадают айди
Ну все верно. Это же таблица лайкнутых фильмов. Он не находит фильм с такми ID потому что его нет.
androidx.room.rxjava3.EmptyResultSetException: Query returned empty result set: SELECT * FROM movie_table WHERE movie_id == ? Здесь вметос вопроса подставляется id фильма для поиска, рум его не находит, а в RX нельзя передавать null поэтому мы сюда и прилетаем

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/movie_details/MovieDetailsFragment.kt
> +            //почему то когда кликаешь(когда сделал на MVVM)
А какая ViewModel используется?

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/tvshows/TvShowsFragment.kt
> +        return binding.root
Тут нужно еще указать         presenter.attachView(this)

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/tvshows/TvShowsFragment.kt
> +        //вроде ошибок нет, но список не отображает((
Выше описал в чем проблема - там view пустая была  и соответственно до этого метода не доходило        view?.showTvShowws(show.results)

2023-01-20 19:48 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/watchlist/WatchlistFragment.kt
> +        binding.moviesRecyclerView.layoutManager = GridLayoutManager(context, 4)
magic number

2023-01-24 04:59 UTC, Dumankrg2019 commented on app/src/main/java/ru/androidschool/intensiv/presentation/ui/tvshows/TvShowsFragment.kt
> +        //вроде ошибок нет, но список не отображает((
Тут не совсем понял. Не работает этот код. Не распознает showTvShowws и show.result - красным помечает, типа как не существует

2023-02-02 17:54 UTC, merged